import { Injectable } from '@angular/core';

import {
  HttpRequest,
  HttpHandler,
  HttpEvent,
  HttpInterceptor
} from '@angular/common/http';

import { SessionManagerService } from './session-manager.service';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})

/**
 * this service has the mission to intercept any http request generated by the application and
 * to add the requested security token has stored into the session manager.
 * likely depending on where the request is directed to, the token might differ.
 * in a future one could also envisage having so called application token added to it to identify
 * and hence monetize the transaction from back end side
 */
export class SecurityTknService implements HttpInterceptor {
  constructor(private session: SessionManagerService) {}

  intercept(
    request: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {
    console.log('interception of request ' + request);
    if (this.session.authToken != null) {
      request = request.clone({
        setHeaders: {
          Authorization: `Bearer ${this.session.authToken}`
        }
      });
      return next.handle(request);
    } else {
      return next.handle(request);
    }
  }
}
