import { Injectable } from '@angular/core';

import {
  HttpRequest,
  HttpHandler,
  HttpEvent,
  HttpInterceptor,
  HttpClient,
  HttpErrorResponse,
  HttpHeaders
} from '@angular/common/http';

import { SessionManagerService } from './session-manager.service';
import { Observable, throwError } from 'rxjs';
import { ConfigService } from './config.service';
import { map, catchError } from 'rxjs/operators';
import { MatSnackBar } from '@angular/material';
import { isUndefined } from 'util';

@Injectable({
  providedIn: 'root'
})

/**
 * this service has the mission to intercept any http request generated by the application and
 * to add the requested security token has stored into the session manager.
 * likely depending on where the request is directed to, the token might differ.
 * in a future one could also envisage having so called application token added to it to identify
 * and hence monetize the transaction from back end side
 */
export class SecurityTknService implements HttpInterceptor {

  constructor(
    private config: ConfigService
    ) {}

// all http request are intercepted
  intercept(
    request: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {
    console.log('interception of request ' + request);
    console.log('add auth token: ' + this.config.authToken);
    if (this.config.authToken != null) {
      request = request.clone({
        setHeaders: {
          Authorization: `Bearer ${this.config.authToken}`
        }
      });
      return next.handle(request);
    } else {
      return next.handle(request);
    }
  }
}
